### ISSUE TITLE
Upgrade process don't work when user interface is translated

### ISSUE THREAD

**Issue by jose-carmona** [bitnami/bitnami-docker-drupal#87]
**Description**

Upgrade process don't work when user interface is translated because the update.php wizard is translated too.  If Spanish language is set as default, the 'Continue' button is translated to 'Continuar'.

**Steps to reproduce the issue:**

1. Login drupal as administrator
1. Active modules 'locale' and 'language'
1. Add Spanish language 
1. Set Spanish language as default
1. Update translations
1. Upgrade bitnami drupal container:
    1. Stop your container
    1. Remove the stopped container
    1. Run the new image

**Describe the results you received:**

With `NAMI_DEBUG=1` and `BASH_DEBUG=1`:
```
drupal_1   | drupal  INFO  Updating Drupal database ...
drupal_1   | Error executing 'postInstallation': No link matching 'Continue'
drupal_1   | nami    TRACE Error: Error executing 'postInstallation': No link matching 'Continue'
drupal_1   |     at Browser.exec (/opt/bitnami/nami/node_modules/nami-core/lib/browser/index.js:447:15)
drupal_1   |     at Object.$app.helpers.passUpdateWizard (/root/.nami/components/com.bitnami.drupal/helpers.js:46:29)
drupal_1   |     at Component.$app.postInstallation (/root/.nami/components/com.bitnami.drupal/main.js:48:18)
drupal_1   |     at Component.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
drupal_1   |     at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
drupal_1   |     at ot (/opt/bitnami/nami/node_modules/lodash/index.js:12:507)
drupal_1   |     at Function.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:33:421)
drupal_1   |     at Component.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
drupal_1   |     at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)
drupal_1   |     at Command.cmdOpts.callback (/opt/bitnami/nami/cli/nami-app.js:331:24)
drupal_1   |     at NamiParser.parseCommands (/opt/bitnami/nami/node_modules/cmd-parser/index.js:518:30)
drupal_1   |     at NamiParser.parse (/opt/bitnami/nami/node_modules/cmd-parser/index.js:742:14)
drupal_1   |     at NamiCliApp.parse (/opt/bitnami/nami/cli/nami-app.js:592:17)
drupal_1   |     at NamiCliApp.exec (/opt/bitnami/nami/cli/nami-app.js:599:12)
drupal_1   |     at Object.<anonymous> (/opt/bitnami/nami/index.js:10:19)
drupal_1   |     at Module._compile (module.js:541:32) 
```

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:12:06 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

- Output of `docker info`:

```
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 9
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.41-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: 4AVZ:WTBA:W4CR:DGK2:SVMC:3SOZ:TQXX:4UB6:Q5KN:3GC7:J4TR:2EUL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 34
 Goroutines: 43
 System Time: 2017-10-01T16:54:49.869704884Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by dbarranco** [comment]
Hi @jose-carmona 

Thank you so much for reporting this.
I have opened an internal task to change the current update method (which is loading a browser and following the web wizard of Drupal) to use drush, but I am afraid I can not give you an ETA. 

By the way, thank you so much for using our Docker images in your project. We're so happy to see this :)

Finally, do not hesitate on asking us if you don't understand something related with any Docker image of Bitnami you're using or if you find any issue.
Best regards!!

**Comment by marcosbc** [comment]
Hi,

Sorry for the delay on getting back to you on this. We changed our Drupal deployment method to Drush a couple of months ago, so this issue should be fixed now.

Best regards
